services:
  app:
    build: .
    container_name: hp-app
    ports:
      - "42069:42069"
    environment:
      - ITEMS_RENDERER_ADDR=http://ir-app-render:8080/
      - IMAGES_PROVIDER_ADDR=http://ip-app:8080/
      - AUTH_ADDR=http://ar-app:8080/
      # - TEMPORAL_ADDR=temporal:7233
      # - TASK_QUEUE=items-repository
    networks:
      - render-network
      # - temporal-network

networks:
  render-network:
    external: true
  # temporal-network:
    # external: true
